train:
  seed: 33
  total_iters: 40000
  dead_weight: 0.3
  patch_size: 256
  dw_warmup: 1500
  dw_alpha: 8.94
  dw_dead_scale: 1.0
  lpips_mask_prob: 0.0
  loss_l1_w: 0.735
  loss_ssim_w: 0.052
  loss_lpips_w: 0.212
  densify_from: 500
  densify_until: 25000
  densify_interval: 100
  max_gaussians: 2500000
  max_grad: 0.0004
  min_opacity_prune: 0.05
  reset_iters:
  - 3000
  - 8000
  - 15000
  - 22000
  floater_prune_iters:
  - 2500
  - 5500
  - 9000
  - 16000
  - 23000
  floater_opacity_thresh: 0.15
  floater_scale_pct: 0.99
